
// http://stackoverflow.com/questions/130396/are-there-constants-in-javascript

var AlertMsgs = (function () {
    var private = {
        "START_CHAR": "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        , "SUBM_ERROR": "Background processes are not completed yet (XKEYX). Please submit the form once again"
        , "ARGS_LEN": "Sorry! Invalid argument length"
        , "NO_AC_ID": "Sorry! Auto Complete ID text box (XKEYX) not found"
        , "UNRG_ERROR": "Sorry! Illegal unregistering of blur function"
        , "NO_BACK_SPACE": "Sorry! Backspace key disabled at this location"
        , "NO_ENTER_KEY": "Sorry! Enter key disabled at this location"
        , "NO_RIGHT_CLICK": "Sorry! Right click disabled due to security reasons"
        , "SAVE_ERROR": "Sorry! Record not saved due to XKEYX. Please try again"
        , "SAVE": "Save"
        , "EDIT": "Edit"
        , "CANCEL": "Cancel"
        , "VIEW": "View"
        , "BLOCK": "Block"
        , "UN_BLOCK": "Unblock"
        , "IS_ACTIVE": "Is Active"
        , "SELECT": "Select"
        , "COMPLETED": "Completed"
        , "DELETE_CONFIRM": "Do you want to delete this record ?"
        , "BLOCK_CONFIRM": "Do you want to block this record ?"
        , "BLOCK_CONFIRM_TEMP": "Do you want to block this record temporarily ?"
        , "DEPROMOTE_CONFIRM": "Do you want to depromote this manager ?"
        , "UN_BLOCK_CONFIRM": "Do you want to unblock this record ?"
        , "NO_REC": "No Records to Display"
        , "ACCENDING": "Accending"
        , "DECENDING": "Decending"
        , "ENLARGE_CLICK": "Click here to enlarge"
        , "PRINT_CLICK": "Click here to print"
        , "DOWNLOAD_CLICK": "Click here to download"
        , "INVALID_DATE": "Please enter a valid date."
        , "INVALID_MEDICARE": "Please enter a valid medicare id"
        , "INVALID_EMAIL": "Please enter a valid email address"
        , "INVALID_WEB": "Please enter a valid web address"
        , "INVALID_PHONE": "Please enter a valid phone number"
        , "INVALID_SSN": "Please enter a valid ssn"
        , "INVALID_ZIP": "Please enter a valid zip code"
        , "INVALID_UPLOAD": "Please upload a valid file (XKEYX)"
        , "REGISTERED_EMAIL": "Please enter registered email address"
        , "USER_NAME": "Please enter your username"
        , "USER_NAME2": "Please enter  username"
        , "PASSWORD_ERR": "Please enter your password"
        , "CHART_NO": "Please enter chart number"
        , "MEDICARE_ID": "Please enter medicare id"
        , "CITY": "City"
        , "ZIP_CODE": "Zip Code"
        , "NAME": "Name"
        , "CODE": "Code"
        , "MEDI_CARE_ID": "Medicare ID"
        , "CHART_NUMBER": "Chart #"
        , "DOS": "DOS"
        , "CLAIMS": "Claims"
        , "CLOSE": "Close"
        , "OPEN": "Open"
        , "TODAY": "Today"
        , "DAYS": "Days"
        , "PATIENT_VISIT_ID": "Case #"
        , "USER_CRED_SUB": "Please enter user credential subject "
        , "SEARCH_REC": "Please enter search results per page "
        , "PAGE_AUTOLOCK": "Please enter page auto lock idle time"
        , "SESSION_TIMEOUT": "Please enter session timeout "
        , "MAX_DAYS_DOC_ATTACH": "Please enter maximum days to complete BA work from DOS "
        , "MAX_DAYS_DOS_CREATE_CLAIM": "Please enter maximum days to complete QA work from DOS"
        , "MAX_DAYS_QA_CLAIM_CONF": "Please enter maximum days to sent EDI file from DOS"
        , "MAX_DAYS_KEEP_STAT_HOLD": "Please enter maximum days to complete the claim process from DOS"
        , "MAX_DAYS_EDIFILE_CREATE": "Please enter maximum days to create EDI file  "
        , "MAX_DAYS_EDI_RESPONSE": "Please enter maximum days for EDI response   "
        , "MAX_DAYS_KEEP_CLAIM_REJECT": "Please enter maximum days for keeping claim status as rejected state from rejected status set date "
        , "MAX_DAYS_CLAIM_ACCEPT": "Please enter maximum days for a claim from Date of Service to Claim Accepted status "
        , "DOCUMENT_CATEGORY_CODE": "Please enter document category code"
        , "DOCUMENT_CATEGORY_NAME": "Please enter document category name"
        , "ILLNESS_INDI_DATE": "Illness Indicator Date"
        , "ILLNESS_INDICATOR_NAME": "Illness Indicator"
        , "ILLNESS_INDICATOR": "Please enter illness indicator"
        , "ILLNESS_INDICATOR_DATE": "Please enter illness indicator date"
        , "CASE_DESC": "Please enter case description"
        , "CASE_DESC1": " Case Description"
        , "DESCR": "Please enter  description"
        , "FACILITY_TYPE": "Please enter facility type"
        , "FACILITY_DONE_NAME": "Please enter facility done"
        , "AMOUNT": "Please enter amount"
        , "PRIME_DX": "Please enter primary dx"
        , "PROCEDURE_ERR": "Please enter procedure"
        , "NOTE_ERR": "Please enter Note"
        , "FACILITY_DONE_NAME1": "Facility Done"
        , "UPLOAD_MAX_SIZE_IN_MB": "Please enter maximum size for document"
        , "LAST_NAME": "Please enter last name"
        , "FIRST_NAME": "Please enter first name"
        , "DATE_OF_BIRTH": "Please enter the date of birth"
        , "PROVIDER_NAME": "Please enter assigned provider name"
        , "MEDICAREID": "Please enter medicare id"
        , "POLICY_NUMBER2": "Please enter policy number"
        , "POLICY_HOLDER_CHART_NUMBER": "Please enter insurance name"
        , "RELATIONSHIP": "Please enter policy holder relationship "
        , "PATIENT_STATE": "Please enter state "
        , "PATIENTRESULT_EMAIL": "Please enter email"
        , "PATIENTRESULT_ISSIGNEDFILE": "Has signed file should be checked"
        , "PATIENT_COUNTRY": "Please enter country "
        , "PATIENT_STREET": "Please enter street 1"
        , "PATIENTRESULT_ISCAPITATED": "Capitated should be checked"
        , "PATIENTRESULT_ISINSURANCEBENEFITACCEPTED": "Insurance benefits accepted should  be checked"
        , "PATIENT_CITY": "Please enter city "
        , "PATIENTRESULT_PHONENUMBER": "Please enter phone number "
        , "RESET_ALERT_CHANGE": "This will reset alert flag in user table . Do you want to continue ?"
        , "USERRESULT_PASSWORD": "Please enter current password"
        , "NWPASSWORD": "Please enter new password"
        , "CONPASSWORD": "Please confirm your new password"
        , "NOMATCH": "The passwords should match"
        , "ADMITTEDON": "Admitted On"
        , "DOCUMENTCATEGORYCODE": "Category code is limited to two characters"
        , "DOCUMENTCATEGORYCODE1": "Please enter Category code "
        , "TIMEOUT_CHECK_ERROR": "Session Timeout should be minimum of 3 times that of page auto lock idle timeout"
        , "DELETE": "Delete"
        , "REMOVE": "Remove"
        , "DX_NAME": "Please enter Dx"
        , "STATE_CODE": "Please enter state code"
        , "STATE_NAME": "Please enter state name"
        , "DOS_ERROR": "Please enter DOS"
        , "PROC_ERROR": "Please enter procedure"
        , "TOTAL_CHARGE": "Please enter total charge"
        , "UNITS": "Please enter units"
        , "EMAIL": "Email"
        , "CLAIM_NUMBER": "Claim #"
        , "CN": "CN"
        , "DX": "Dx"
        , "POINTING_DX": "Pointing DX"
        , "DIAGNOSIS": "Diagnosis"
        , "PROCEDURE": "Procedure"
        , "DEL_PROC": "Delete Procedure"
        , "PROC": "Proc"
        , "FAC_TYPE": "Facility Type"
        , "FACILITY": "Facility"
        , "MODI1": "Modifier Name 1"
        , "MODI2": "Modifier Name 2"
        , "MODI3": "Modifier Name 3"
        , "MODI4": "Modifier Name 4"
        , "M1": "M1"
        , "M2": "M2"
        , "M3": "M3"
        , "M4": "M4"
        , "UNITS_PRO": "Units"
        , "UNS": "UNIT"
        , "CHR_UNIT": "Charge Per Unit"
        , "CHR": "Charge"
        , "CHR_TOT": "Total Charge"
        , "TOT": "Total"
        , "DETAILED_VIEW": "Detailed View"
        , "MSG_CODE": "Please enter code"
        , "MSG_NAME": "Please enter name"
        , "MSG_ZIPCODE": "Please enter zip code"
        , "INSURANCETYPE": "Insurance Type"
        , "PAYERID": "Payer ID"
        , "LASTNAME": "Last Name"
        , "LASTNAME2": "Please enter last name"
        , "FNAME": "First Name"
        , "FNAME2": "Please enter first name"
        , "MID_NAME": "Middle Name"
        , "SEX": "Sex"
        , "DOB": "DOB"
        , "SSN": "SSN"
        , "ASGN_PVDR_NAME": "Assigned Provider Name"
        , "INSURANCE_NAME": "Insurance Name"
        , "EDI_RECEIVER1": "EDI Receiver"
        , "POLICY_NUMBER": "Policy #"
        , "GROUP_NUMBER": "Group #"
        , "POL_HOLD_REL": "Policy Holder Relationship"
        , "POL_HOLD_CHART_NO": "Policy Holder Chart No"
        , "YES": "Yes"
        , "NO": "No"
        , "INSU_BEN_ACCEPTED": "Insurance Benefits Accepted?"
        , "CAPITATED": "Capitated?"
        , "INSU_EFF_FROM": "Insurance Effective From"
        , "INSU_EFF_TO": "Insurance Effective To"
        , "HAS_SIGN_FILE": "Has Signed File?"
        , "SIGN_DATE": "Signed Date"
        , "CONT_DETAILS": "Contact Details"
        , "STREET": "Street 1"
        , "SUITE_NO": "Street 2"
        , "STATE": "State"
        , "COUNTRY": "Country"
        , "COUNTY": "County"
        , "PH_NUMBER": "Phone #"
        , "SEC_PH_NUMBER": "Secondary Phone #"
        , "SEC_EMAIL": "Secondary Email"
        , "PHOTO": "Photo"
        , "COMMENT": "Comments"
        , "PERS_DETAILS": "Personal Details"
        , "NPI": "NPI"
        , "SHORTDESC": "Short Description"
        , "AUTH_INFO_QUALI": "Author Info Qualifier (ISA01)"
        , "AUT_INFO": "Author Info (ISA02)"
        , "SECU_INFO_QUALI": "Security Info Qualifier (ISA03)"
        , "SECU_INFO": "Security Info (ISA04)"
        , "SECURITY_INFO_QUALIFIER_UNAME": "Security Information Qualifier Username"
        , "SECURITY_INFO_QUALIFIER_PWD": "Security Information Qualifier Password"
        , "LAST_INTERCHANGE_CNTRL_NO": "Last Interchange Control Number "
        , "SENDER_INTERCHANGE_QUALIFIER": "Sender Interchange Qualifier"
        , "RECEIVER_INTERCHANGE_QUALIFIER": "Receiver Interchange Qualifier"
        , "RECEIVER_INTERCHANGE_ID": "Receiver Interchange ID"
        , "TRANSACTION_PURPOSE_CODE": "Transaction Set Purpose Code"
        , "TRANSACTION_TYPE_CODE": "Transaction Type Code"
        , "SENDER_INTERCHANGE_ID": "Sender Interchange ID"
        , "CLAIM_MEDIA": "Claim Media"
        , "GS02": "GS02"
        , "GS03": "GS03"
        , "INTERCHANGE_USAGE_INDICATOR": "Interchange Usage Indicator"
        , "SUBMITTER_ENTITY_IDENTIFIER_CODE": "Submitter Entity Identifier Code"
        , "RECEIVER_ENTITY_IDENTIFIER_CODE": "Receiver Entity Identifier Code"
        , "BILLING_PROVIDER_ENTITY_IDENTIFIER_CODE": "Billing Provider Entity Identifier Code"
        , "SUBSCRIBER_ENTITY_IDENTIFIER_CODE": "Subscriber Entity Identifier Code"
        , "PAYER_ENTITY_IDENTIFIER_CODE": "Payer Entity Identifier Code"
        , "ENTITY_TYPE_QUALIFIER": "Entity Type Qualifier"
        , "CURRENCY_CODE_NAME": "Currency Code"
        , "PAYER_RESPONSIBILITY_SEQUENCE_NUMBER_CODE": "Payer Responsibility Sequence Number Code"
        , "EMAIL_COMMUNICATION_NUMBER_QUALIFIER": "Email Communication Number Qualifier"
        , "FAX_COMMUNICATION_NUMBER_QUALIFIER": "Fax Communication Number Qualifier"
        , "PHONE_COMMUNICATION_NUMBER_QUALIFIER": "Phone Communication Number Qualifier"
        , "PATIENT_ENTITY_TYPE_QUALIFIER": "Patient Entity Type Qualifier"
        , "PROVIDER_ENTITY_TYPE_QUALIFIER": "Provider Entity Type Qualifier"
        , "INSURANCE_ENTITY_TYPE_QUALIFIER": "Insurance Entity Type Qualifier"
        , "INTER_SENDER_ID": "Inter Sender ID (ISA06)"
        , "INTER_RCVER_ID": "Inter Receiver ID (ISA07)"
        , "APP_SENDER_CODE": "Application Sender Code (GS02)"
        , "APP_RCVER_CODE": "Application Receiver Code (GS03)"
        , "PASSWORD": "Password"
        , "RCVER_CARRIER": "Receiver Carrier"
        , "RCVER_ID": "Receiver ID"
        , "TRANS_PURPOSE_CODE": "Trans Purpose Code"
        , "TRANS_TYPE_CODE": "Trans Type Code"
        , "USAGE_INDICATOR": "Usage Indicator"
        , "IS_GROUP_PRACTICE": "Is Group Practice?"
        , "LAST_FILE_ID": "Last File ID"
        , "BLOCK_STATUS": "Block Status"
        , "OFFICE_ADDRESS": "Office Address"
        , "EXTENSION": "Extension"
        , "FAX": "Fax #"
        , "EDI_RECEIVER_NAME": "EDI Receiver Name"
        , "PRINT_PIN_ON_FILE": "Print PIN on File"
        , "PRINT_SIGN_ON_FILE_PAT": "Print Sign On File - Patient"
        , "PRINT_SIGN_ON_FILE_INS": "Print Sign On File - Insured"
        , "PRINT_SIGN_ON_FILE_PROV": "Print Sign On File - Physician / Provider"
        , "CLINIC_NAME": "Clinic Name"
        , "CREDENTIAL": "Credential"
        , "CRED": "Please enter credential"
        , "TAX_ID": "Tax ID"
        , "PRIMARY_OPTION": "Primary Option"
        , "SPECIALTY": "Specialty"
        , "LICENSE_NUMBER": "License #"
        , "CLIA_NUMBER": "CLIA #"
        , "CONTACT_PERSON_DETAILS": "Contact Person Details"
        , "ENTITY_TYPE": "Entity Type"
        , "LOGO": "Logo"
        , "CLAIM_STATUS": "Claim Status"
        , "ASSIGNED_TO": "Assigned To"
        , "ASSIGNEE": "Assignee"
        , "START_DATE": "Start On"
        , "END_DATE": "End On"
        , "START_END_MINUTES": "Start End Minutes"
        , "LOGOUT_LOGIN_MINUTES": "Logout-Login Minutes"
        , "LOCK_UNLOCK_MINUTES": "Lock-Unlock Minutes"
        , "DURATION": "Duration"
        , "ICD_FORMAT1": "ICD Format"
        , "IPA_NAME": "IPA"
        , "MANAGER_NAME1": "Manager Name"
        , "IS_PATIENT_DEMOGRAPHICS_PULL": "Is patient demographics pull?"
        , "IS_PAT_VISIT_DOC_MANADATORY": "Is patient visit document mandatory?"
        , "FACILITY_TYPE_NAME": "Facility Type"
        , "SHORT_NAME": "Short Name"
        , "PATIENT_VISIT_COMPLEXITY": "Patient visit complexity"
        , "DOC_CATEGORY": "Document Category"
        , "CATEGORY": "Category"
        , "SERVICE_DATE": "Service Date"
        , "TO_DATE": "To date"
        , "DOCUMENT": "Document"
        , "DETAILS": "Details"
        , "ICD_FORMAT": "Please enter ICD format"
        , "SHORT_DESC": "Please enter the short description"
        , "MEDIUM_DESC": "Please enter the medium description"
        , "LONG_DESC": "Please enter the long description"
        , "CUSTOM_DESC": "Please enter the custom description"
        , "CHARGE_PER_UNIT": "Please enter charge per unit"
        , "IS_HCPCS_CODE": "HCPS code should be checked "
        , "AUTH_ID": "Please enter author info qualifier (ISA01)"
        , "RECEIVER_NAME": "Please enter receiver name"
        , "SPEC": "Please enter specialty"
        , "AUTHORIZATION_INFO": " Please enter author info (ISA02)"
        , "SECURITY_ID": "Please enter security information qualifier"
        , "INTER_SENDERID": "Please enter sender interchange qualifier"
        , "INTER_RECEIVERID": "Please enter inter receiver ID (ISA07)"
        , "RECEIVERID": "Please enter receiver ID "
        , "APPLN_SENDER_CODE": "Please enter GS02"
        , "APPLN_RECEIVER_CODE": "Please enter GS03"
        , "RECEIVER_CARRIER": "Please enter receiver carrier"
        , "USAGEINDICATOR_ID": "Please enter interchange usage indicator"
        , "SUBMITTER_ENTITYIDENTIFIER_CODE": "Please enter submitter entity identifier code"
        , "RECEIVER_ENTITYIDENTIFIER_CODE": "Please enter receiver entity identifier code"
        , "ENTITYTYPE_QUALIFIER": "Please enter entity type qualifier "
        , "CURRENCY_CODE": "Please enter currency code"
        , "PAYER_RESPONSIBILITY_SEQUENCENUMBER_CODE": "Please enter payer responsibility sequence number code"
        , "MSG_COMPLEXITY": "Please enter patient visit complexity "
        , "EMAIL_COMMUNICATION_NUMBERQUALIFIER": "Please enter email communication number qualifier"
        , "FAX_COMMUNICATIONNUMBER_QUALIFIER": "Please enter fax communication number qualifier"
        , "PHONE_COMMUNICATIONNUMBER_QUALIFIER": "Please enter phone communication number qualifier"
        , "PATIENT_ENTITYTYPE_QUALIFIER": "Please enter patient entity type qualifier"
        , "PROVIDER_ENTITYTYPE_QUALIFIER": "Please enter provider entity type qualifier"
        , "INSURANCE_ENTITYTYPE_QUALIFIER": "Please enter insurance entity type qualifier"
        , "BILLINGPROVIDER_ENTITYIDENTIFIER_CODE": "Please enter billing provider entity identifier code"
        , "SUBSCRIBER_ENTITYIDENTIFIER_CODE": "Please enter subscriber entity identifier code"
        , "PAYER_ENTITYIDENTIFIER_CODE": "Please enter payer entity identifier code"
        , "FUNCTIONAL_IDENTIFIER_CODE_ERR": "Please enter functional identifier code"
         , "FUNCTIONAL_IDENTIFIER_CODE": "Functional Identifier Code"
        , "SENDER_INTERCHANGEID": "Please enter sender interchange id"
        , "RECEIVER_INTERCHANGEID_QUALIFIER": "Please enter receiver interchange qualifier"
        , "RECEIVER_INTERCHANGEID": "Please enter receiver interchange id"
        , "SECURITY_INFO": "Please enter security info (ISA04)"
        , "MODI_ORDER_ERROR": "Without lower level you can not fill higher level modifiers"
        , "MAX_VAL_ERROR": "Sorry! Value should not exceed 999999.99"
        , "EXPAND": "Expand"
        , "COLLAPSE": "Collapse"
        , "HOSPITAL_NAME": "Please enter the hospital name"
        , "ADMITTED_ON": "Please enter the admitted date"
        , "MAX_DIAGNOSIS": "Please enter Max Diagnosis"
        , "PAYER_ID": "Please enter payer ID"
        , "INSURANCE_TYPE": "Please enter insurance type"
        , "EDI_RECEIVER": "Please enter EDI receiver"
        , "PRINT_PIN": "Please enter print pin on file"
        , "PATIENT_PRINTSIGN_ID": "Please enter print sign on file - patient"
        , "PHYSICIAN_PRINT_SIGNID": "Please enter print sign on file – physician / provider"
        , "INSURED_PRINT_SIGN": " Please enter print sign on file - insured"
        , "LAST_INTERCHANGE_CONTROL_NUMBER": "Please enter last interchange control number"
        , "MSG_NPI": "Please enter NPI "
        , "MSG_TAX": "Please enter Tax ID"
        , "ENTITY_TYPEMSG": "Please enter Entity Type"
        , "X12": "X12"
        , "REF": "Ref"
        , "SEL_DX_LIST": "Selected Dx List"
        , "BLOCKED_DX_LIST": "Blocked Dx List"
        , "NO_BLOCKED_DX": "No blocked Dxs"
        , "BLOCKED_CPT_LIST": "Blocked Procedure List"
        , "NO_BLOCKED_CPT": "No blocked procedures"
        , "BLOCKED_VISIT": "This Visit is  blocked"
        , "NO_BLOCKED_VISIT": "This Visit is not blocked"
        , "BLOCKED": "Blocked"
        , "EDI_FILE": "EDI File"
        , "DESC": "Atleast one description is mandatory"
        , "DESC1": "Description"
        , "MSG_COUNTRY": "Please enter Country Name"
        , "NO_PROCEDURE": "*** NO PROCEDURE ***"
        , "HOSP_NAME": "Hospital Name"
        , "IS_HOSP": "Hospitalized"
        , "CLINIC_CODE": "Clinic Code"
        , "DOC_NOTES": "Doctor Notes"
        , "SUPERBILLS": "Superbills"
        , "PRIMARY_DX": "Primary Diagnosis"
        , "MANAGER_NAME": "Please enter manager"
        , "CLINIC_IPA": "Please enter billing / IPA"
        , "INSURANCE_NAME2": "Please enter insurance name"
        , "CLAIM_MEDIAID": "Please enter claim media"
        , "TRANSACTION_PURPOSECODE_ID": "Please enter transaction set purpose code"
        , "TRANSACTION_TYPE_CODE_ERR": "Please enter transaction type code"
        , "MIN_LENGTH_ERR": "Please enter minimum length"
        , "MAX_LENGTH_ERR": "Please enter maximum length"
        , "UPPER_CASE_MIN_COUNT_ERR": "Please enter upper cases minimum count"
        , "NUM_MIN_COUNT_ERR": "Please enter numbers minimum count"
        , "SPECIAL_CHAR_MIN_COUNT_ERR": "Please enter special characters minimum count"
        , "PWD_AGE_ERR": "Please enter maximum password age"
        , "TRIAL_MAX_COUNT_ERR": "Please enter password trail maximum count"
        , "REUSE_STAT_ERR": "Please enter history password re-using status"
        , "PWD": "Please enter password"
        , "ICDFORMAT": "ICD Format"
        , "NOT_IN_TRACK": "Not In Track"
        , "MSG_ALPHA": "Starting letter should be an alphabet"
        , "SUMMARY": "Summary"
        , "DISCHARGED_ON": "Discharged On"
        , "DX_DEL_ERROR": "Sorry. You cannot delete this dx, because it is set as primary dx."
        , "NOTES": "Notes"
        , "PROCEDURE_DETAIL": "Procedure List Detail"
        , "COMPLEXITY": "Complexity"
        , "TAT": "Turn Around Time"
        , "ASSIGN_TO_ME": "Assign"
        , "CREATED_ON": "Created On"
        , "SL_NO": "Sl No"
        , "USERS_WITHOUT_ROLE": "Users Without Role"
        , "USERS_WITHOUT_CLINIC": "Users Without  Clinic"
        , "MANAGER_WITHOUT_AGENT": "Manager Without Agent"
        , "CLINICS_WITHOUT_MANAGER": "Clinics Without Manager"
        , "CLINICS_WITH_MANY_MANAGERS": "Clinics With Many Managers"
        , "NOTIFICATION": "Notification"
        , "VISITS": "Visits"
        , "CREATED": "Created"
        , "HOLD": "Hold"
        , "READY_TO_SEND": "Ready To Send"
        , "SENT": "Sent"
        , "ACCEPTED": "Accepted"
        , "REJECTED": "Rejected"
        , "RESUBMITTED": "Re-submitted"
        , "MONTH": "Month"
        , "DAY": "Day"
        , "YEAR": "Year"
        , "IN_PROGRESS": "In-Progress"
        , "DONE": "Done"
        , "ASSIGNED_CLINICS": "Assigned Clinics"
        , "AGENTS": "Agents"
        , "NO_DATA": "No data to display"
        , "ENTER_DX_FIRST": "Please enter Dx first"
    };

    return {
        get: function (name) { return private[name]; }
    };
})();